"""Generate one OWL-D fine-tuning config per (arm, fold).

Derived from the authors' released benchmark config
`exp_dpt_vith_focal_sum_norm_frozen_benchmark.yaml`, changed in exactly three
ways so the result is still recognisably their recipe:

  * `load_from` points at the released OWL-D.pth, so we FINE-TUNE their trained
    decoder rather than training one from scratch. `pretrained` goes false
    because the weights now come from that checkpoint.
  * the datasets point at our patches.
  * epochs 20 -> 10. Twenty was for from-scratch training on a merged
    five-dataset corpus; starting from a converged decoder needs far fewer, and
    `auto_lr` on f1_score plus `select_mode: max` already guard against
    under-training.

Optimiser, learning rate, batch size, loss, augmentations, the frozen backbone
and the evaluator are left exactly as published. Deviating on those would make
"fine-tuned OWL-D" a model of our own tuning rather than theirs.
"""
from __future__ import annotations

import argparse
from pathlib import Path

TEMPLATE = """# OWL-D fine-tuned on BAMBI {arm} fold {fold}.
# Generated by owl_make_configs.py from the authors' benchmark config.
wandb_project: 'bambi-owld-finetune'
wandb_entity: 'anonymous'
wandb_run: 'owld_ft_{arm}_f{fold}'
use_wandb: false
seed: {seed}
device_name: cuda

model:
  name: OWLD_H
  from_torchvision: false
  load_from: '{ckpt}'
  partial_load: false
  resume_from: null
  # Required whenever load_from is set: train.py reads cfg.model.freeze directly
  # (not via getattr) inside the load_from branch, which the from-scratch
  # benchmark config never enters. null means no EXTRA layer freezing beyond
  # freeze_backbone below.
  freeze: null
  kwargs:
    pretrained: false
    head_conv: 64
    readout_type: ignore
    freeze_backbone: {freeze_backbone}
    down_ratio: 2

losses:
  FocalLoss:
    print_name: focal_loss
    from_torch: false
    output_idx: 0
    target_idx: 0
    lambda_const: 1.0
    kwargs:
      reduction: sum
      normalize: true

datasets:
  img_size: [512, 512]
  anno_type: point
  collate_fn: null
  class_def:
    1: 'animal'

  train:
    name: FolderDataset
    csv_file: '{train_dir}/gt.csv'
    root_dir: '{train_dir}'
    sampler: null
    albu_transforms:
      VerticalFlip:
        p: 0.5
      HorizontalFlip:
        p: 0.5
      RandomRotate90:
        p: 0.5
      RandomBrightnessContrast:
        brightness_limit: 0.2
        contrast_limit: 0.2
        p: 0.2
      Blur:
        blur_limit: 15
        p: 0.2
      Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    end_transforms:
      FIDT:
        add_bg: false
        down_ratio: 2

  validate:
    name: CSVDataset
    csv_file: '{val_dir}/gt.csv'
    root_dir: '{val_dir}'
    albu_transforms:
      Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    end_transforms:
      DownSample:
        down_ratio: 2
        anno_type: point

training_settings:
  trainer: Trainer
  valid_freq: 1
  print_freq: 100
  batch_size: {batch}
  optimizer: adam
  lr: 3.0e-4
{backbone_lr_line}  weight_decay: 0.0005
  warmup_iters: 50
  vizual_fn: null
  epochs: {epochs}
  auto_lr:
    mode: max
    patience: 3
    threshold: 1.0e-4
    threshold_mode: rel
    cooldown: 1
    min_lr: 1.0e-5
  evaluator:
    name: HerdNet_Detection_Branch_Evaluator
    threshold: 30
    select_mode: max
    validate_on: f1_score
    kwargs:
      print_freq: 10
      lmds_kwargs:
        kernel_size: [5, 5]
        adapt_ts: 0.2
  stitcher:
    name: HerdNet_Detection_Branch_Stitcher
    kwargs:
      overlap: 160
      down_ratio: 2
      up: false
      reduction: mean
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", type=Path, required=True,
                    help="configs/train/ of the vendored repo")
    ap.add_argument("--data-root", type=Path,
                    default=Path("/scratch/bambi/owl/train_data"))
    ap.add_argument("--ckpt", default="/scratch/bambi/owl/ckpt/OWL-D.pth")
    ap.add_argument("--arms", default="ortho_rgb,alfs_rgb")
    ap.add_argument("--folds", default="0,1,2,3,4")
    ap.add_argument("--epochs", type=int, default=10)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--name-prefix", default="bambi_owld_ft")
    ap.add_argument("--unfrozen", action="store_true",
                    help="Train the DINOv3 backbone too. Adds gradients and "
                         "Adam states for 840M params on top of activations, so "
                         "--batch must come down or the 40GB card OOMs.")
    ap.add_argument("--batch", type=int, default=16)
    ap.add_argument("--backbone-lr-factor", type=float, default=None,
                    help="Scales the backbone LR relative to the head. Only "
                         "meaningful with --unfrozen; train.py reads it via "
                         "getattr so omitting it is safe.")
    args = ap.parse_args()

    n = 0
    for arm in args.arms.split(","):
        for fold in args.folds.split(","):
            train_dir = args.data_root / f"{arm}_f{fold}_train"
            val_dir = args.data_root / f"{arm}_f{fold}_val"
            name = f"{args.name_prefix}_{arm}_f{fold}"
            blr = ("" if args.backbone_lr_factor is None
                   else f"  backbone_lr_factor: {args.backbone_lr_factor}\n")
            (args.out_dir / f"{name}.yaml").write_text(
                TEMPLATE.format(arm=arm, fold=fold, ckpt=args.ckpt,
                                train_dir=train_dir, val_dir=val_dir,
                                epochs=args.epochs, seed=args.seed,
                                batch=args.batch,
                                freeze_backbone=str(not args.unfrozen).lower(),
                                backbone_lr_line=blr),
                encoding="utf-8")
            n += 1
            print(f"  {name}.yaml  train={train_dir.name} val={val_dir.name}")
    print(f"[done] {n} configs -> {args.out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
